name: weather_checker

on:
  schedule:
    - cron: '0 14 * * *' # runs at 14:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: execute py script 
        env: 
          DESTINATION_PHONE_NUMBER: ${{ secrets.DESTINATION_PHONE_NUMBER }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          FORECAST_URL: "https://api.weather.gov/gridpoints/LWX/114,80/forecast/hourly"
        run: python weather.py $FORECAST_URL
          
          
