name: weather_checker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 14 * * *' # runs at 14:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: install js packages
        run: bun install
          
      - name: execute js script 
        env: 
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: $${ secrets.PUSHOVER_TOKEN }}
        run: bun run weather.ts
          