name: weather_checker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 14 * * *' # runs at 14:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: setup python
        uses: actions/setup-python@v4
          
      - name: execute py script 
        env: 
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        run: python weather.py
          
          
