name: weather_checker

on:
  schedule:
    - cron: '37 8 * * *' # 4:37am Eastern DST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Check weather, send email
        env:
          NOTIFY_PROVIDER: resend
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          FORECAST_URL: "https://api.weather.gov/gridpoints/LWX/114,80/forecast/hourly"
        run: bundle exec ruby weather.rb $FORECAST_URL
