name: testing

on:
  schedule:
    - cron: '*/15 * * * *' # hourly testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Send test email
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: bundle exec ruby send_test_email.rb
